# Coolify Configuration for Storage Boxx PHP Inventory Management System
# This file tells Coolify how to deploy this application

# Use Nixpacks for PHP deployment
type: nixpacks
build_pack: nixpacks

# Port mapping - Coolify handles external access via reverse proxy
# No explicit port mapping needed

# Health check endpoint - Check Nginx status
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost/health"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s

# Environment variables (these will be set in Coolify UI)
environment:
  - APP_ENV=production
  - APP_DEBUG=false
  - APP_URL=https://inventory.thesupplycircuit.co

# Domain configuration
domains:
  - inventory.thesupplycircuit.co

# SSL/TLS configuration
ssl: true

# Build configuration - FORCE Docker Compose
build:
  # Use Docker Compose for building - ignore auto-detection
  dockerfile: Dockerfile
  context: .
  build_pack: docker-compose
  
# Disable auto-detection
auto_deploy: false
static_site: false

# Restart policy
restart: unless-stopped

# Labels for Coolify management
labels:
  - "coolify.managed=true"
  - "coolify.type=docker-compose"
  - "coolify.name=storage-boxx"