[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.pdo_pgsql", "php82Extensions.mbstring", "php82Extensions.zip", "php82Extensions.gd"]

[phases.build]
cmds = [
    "mkdir -p /app/storage",
    "mkdir -p /app/bootstrap/cache",
    "chmod -R 777 /app/storage",
    "chmod -R 777 /app/bootstrap/cache",
]

[variables]
PHP_VERSION = "8.2"
APP_URL = "https://inventory.thesupplycircuit.co"
APP_ENV = "production"
APP_DEBUG = "false"
